from datetime import date, timedelta

import pytest

from cfa_config_generator.utils.epinow2.constants import (
    all_diseases,
    all_states,
    nssp_states_omit,
)
from cfa_config_generator.utils.epinow2.functions import (
    extract_user_args,
    generate_default_job_id,
    generate_timestamp,
    validate_args,
)


def test_extract_user_args(monkeypatch):
    """Tests default set of extract_user_args."""
    today = date.today()
    as_of_date = generate_timestamp()
    max_reference_date = today - timedelta(days=1)
    min_reference_date = today - timedelta(weeks=8)

    # Mock environment variables
    monkeypatch.setenv("report_date", today.isoformat())
    monkeypatch.setenv("production_date", today.isoformat())
    monkeypatch.setenv(
        "reference_dates",
        f"{min_reference_date.isoformat()},{max_reference_date.isoformat()}",
    )
    monkeypatch.setenv("data_container", "nssp-etl")
    monkeypatch.setenv("output_container", "test-container")
    # Let job_id be generated by default

    default_args = {
        "task_exclusions": None,
        "exclusions": None,
        "state": "all",
        "disease": "all",
        # Expect date object
        "report_date": today,
        # Expect date object
        "production_date": today,
        # Expect list[date]
        "reference_dates": [
            min_reference_date,
            max_reference_date,
        ],
        "data_path": f"gold/{today.isoformat()}.parquet",
        "data_container": "nssp-etl",
        # Will be generated
        "job_id": generate_default_job_id(as_of_date=as_of_date),
        "as_of_date": as_of_date,
        "output_container": "test-container",
    }

    extracted_args = extract_user_args(as_of_date=as_of_date)

    # Compare all keys except job_id which is non-deterministic
    assert {k: v for k, v in extracted_args.items() if k != "job_id"} == {
        k: v for k, v in default_args.items() if k != "job_id"
    }
    assert "Rt-estimation" in extracted_args["job_id"]


def test_validate_args_default():
    """Tests validate_args with default arguments."""
    report_date = production_date = date.today()
    as_of_date = generate_timestamp()
    max_reference_date = report_date - timedelta(days=1)
    min_reference_date = report_date - timedelta(weeks=8)

    default_args = {
        "state": "all",
        "disease": "all",
        "exclusions": None,
        # Pass date object
        "report_date": report_date,
        # Pass date object
        "production_date": production_date,
        # Pass list[date]
        "reference_dates": [min_reference_date, max_reference_date],
        "data_path": f"gold/{report_date.isoformat()}.parquet",
        "data_container": None,
        "job_id": "test-job-id",
        "as_of_date": as_of_date,
        "output_container": "test-container",
    }

    validated_args = validate_args(**default_args)
    assert validated_args == {
        "state": list(set(all_states) - set(nssp_states_omit)),
        "disease": all_diseases,
        "exclusions": None,
        "reference_dates": [min_reference_date, max_reference_date],
        "report_date": report_date,
        "data_path": f"gold/{report_date.isoformat()}.parquet",
        "data_container": None,
        "production_date": date.today(),
        "job_id": "test-job-id",
        "as_of_date": as_of_date,
        "output_container": "test-container",
    }


def test_invalid_state():
    """Tests that an invalid state raises a ValueError."""
    today = date.today()
    args = {
        "state": "invalid",
        "disease": "all",
        "report_date": today,
        "reference_dates": [today - timedelta(days=1), today - timedelta(days=2)],
        "data_path": "gold/",
        "data_container": None,
        "production_date": today,
        "job_id": "test-job-id",
        "as_of_date": generate_timestamp(),
        "output_container": "test-container",
    }
    with pytest.raises(ValueError):
        validate_args(**args)


def test_invalid_disease():
    """Tests that an invalid disease raises a ValueError."""
    today = date.today()
    args = {
        "state": "all",
        "disease": "invalid",
        "report_date": today,
        "reference_dates": [today - timedelta(days=1), today - timedelta(days=2)],
        "data_path": "gold/",
        "data_container": None,
        "production_date": today,
        "job_id": "test-job-id",
        "as_of_date": generate_timestamp(),
        "output_container": "test-container",
    }
    with pytest.raises(ValueError):
        validate_args(**args)


def test_invalid_reference_date_logic():
    """Tests that reference dates after report date raise ValueError."""
    today = date.today()
    args = {
        "state": "all",
        "disease": "all",
        "report_date": today,
        # Invalid logic
        "reference_dates": [
            today + timedelta(days=1),
            today + timedelta(days=2),
        ],
        "data_path": "gold/",
        "data_container": None,
        "production_date": today,
        "job_id": "test-job-id",
        "as_of_date": generate_timestamp(),
        "output_container": "test-container",
    }
    with pytest.raises(
        ValueError, match="Ensure all reference_dates are on or before the report date"
    ):
        validate_args(**args)


def test_invalid_disease_exclusion():
    """Tests that an invalid disease raises a ValueError."""
    today = date.today()
    as_of_date = generate_timestamp()
    # valid diseases are 'COVID-19' or 'Influenza'
    task_exclusions = "WA:monkeypox"

    args = {
        # Use a valid state for this test focus
        "state": "WA",
        "disease": "all",
        "report_date": today,
        "reference_dates": [today - timedelta(days=1), today - timedelta(days=2)],
        "data_path": "gold/",
        "data_container": None,
        "production_date": today,
        "job_id": "test-job-id",
        "as_of_date": as_of_date,
        "task_exclusions": task_exclusions,
        "output_container": "test-container",
    }

    with pytest.raises(ValueError, match="Disease monkeypox not recognized"):
        validate_args(**args)
