name: re-run-workload
description: Run the re-run workload, which reads a data exclusion/outlier CSV and
  creates config files for just the states/diseases that need to be re-run.

on:
  workflow_dispatch:
    inputs:
      report_date:
        description: 'Report date (default: today; format: YYYY-MM-DD)'
      data_exclusions_path:
        description: 'The path to the data exclusion CSV file. If in Blob, use form `az://<container-name>/<path>` (default: `az://nssp-rt-v2/outliers/<report_date>.csv`)'
      reference_dates:
        description: 'Reference dates (default: [8 weeks before, 1 day before] report date; format: YYYY-MM-DD, YYYY-MM-DD)'
      data_container:
        description: 'Data path (default: None)'
      production_date:
        description: 'Production date (default: today; format: YYYY-MM-DD)'
      job_id:
        description: 'Job ID (default: Rt-estimation-<timestamp>-<uuid>)'
      output_container:
        description: 'Output container in Azure (default: nssp-rt-testing)'

jobs:
  run-workload:
    runs-on: cfa-cdcgov
    environment: production
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Azure Service Principal CLI login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.EDAV_CFA_PREDICT_NNHT_SP }}

    - name: Execute workload script
      run: |
        reference_dates=${{ inputs.reference_dates }} \
        report_date=${{ inputs.report_date }} \
        data_container=${{ inputs.data_container }} \
        production_date=${{ inputs.production_date }} \
        job_id=${{ inputs.job_id }} \
        output_container=${{ inputs.output_container }} \
        data_exclusions_path=${{ inputs.data_exclusions_path }} \
          uv run python pipelines/epinow2/generate_rerun_config.py
