name: re-run-workload
description: Run the re-run workload, which reads a data exclusion/outlier CSV and
  creates config files for just the states/diseases that need to be re-run.

on:
  workflow_dispatch:
    inputs:
      report_date:
        description: 'Report date (default: today; format: YYYY-MM-DD)'
      data_exclusions_path:
        description: 'The path to the data exclusion CSV file. If in Blob, use form `az://<container-name>/<path>` (default: `az://nssp-rt-v2/outliers/<report_date>.csv`)'
      reference_dates:
        description: 'Reference dates (default: [8 weeks before, 1 day before] report date; format: YYYY-MM-DD, YYYY-MM-DD)'
      data_container:
        description: 'Data path (default: None)'
      production_date:
        description: 'Production date (default: today; format: YYYY-MM-DD)'
      job_id:
        description: 'Job ID (default: Rt-estimation-<timestamp>-<uuid>)'
      output_container:
        description: 'Output container in Azure (default: nssp-rt-testing)'

jobs:
  run-workload:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4

    # From: https://stackoverflow.com/a/58035262/2097171
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: get-branch

    # From: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#requesting-the-jwt-using-the-actions-core-toolkit
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v7
      id: idtoken
      with:
        script: |
          const coredemo = require('@actions/core')
          const id_token = await coredemo.getIDToken('api://AzureADTokenExchange')
          coredemo.setOutput('id_token', id_token)

    - name: Re-run workload
      uses: CDCgov/cfa-actions/runner-action@v1.3.0
      with:
        github_app_id: ${{ secrets.CDCENT_ACTOR_APP_ID }}
        github_app_pem: ${{ secrets.CDCENT_ACTOR_APP_PEM }}
        wait_for_completion: true
        print_logs: true
        script: |
          CURRENT_BRANCH="${{ steps.get-branch.outputs.branch }}"
          echo "Cloning repo at branch '$CURRENT_BRANCH'"
          git clone -b "$CURRENT_BRANCH" https://github.com/${{ github.repository }}.git
          cd cfa-config-generator

          echo "Logging into Azure CLI"
          az login --output none --service-principal \
            --username ${{ secrets.EDAV_CFA_PREDICT_NNHT_SP_CLIENT_ID }} \
            --tenant ${{ secrets.AZ_TENANT_ID }} \
            --federated-token ${{ steps.idtoken.outputs.id_token }}

          PYTHON_VERSION="$(cat .python-version)"
          echo "Installing python $PYTHON_VERSION"
          pyenv install "$PYTHON_VERSION"
          pyenv local "$PYTHON_VERSION"

          echo "Installing uv"
          pip install uv

          reference_dates=${{ inputs.reference_dates }} \
          report_date=${{ inputs.report_date }} \
          data_container=${{ inputs.data_container }} \
          production_date=${{ inputs.production_date }} \
          job_id=${{ inputs.job_id }} \
          output_container=${{ inputs.output_container }} \
          data_exclusions_path=${{ inputs.data_exclusions_path }} \
            uv run python pipelines/epinow2/generate_rerun_config.py
