name: run-workload
description: Run a workload to create a new modeling job and associated task configs.

on:
  push: #TODO: remove this!
    branches:
      - gio-runner-migration
  workflow_dispatch:
    inputs:
      state:
        description: 'State to run (default: all)'
      disease:
        description: 'Disease to run (default: all)'
      report_date:
        description: 'Report date (default: today; format: YYYY-MM-DD)'
      reference_dates:
        description: 'Reference dates (default: [8 weeks before, 1 day before] report date; format: YYYY-MM-DD, YYYY-MM-DD)'
      data_container:
        description: 'Data path (default: None)'
      production_date:
        description: 'Production date (default: today; format: YYYY-MM-DD)'
      job_id:
        description: 'Job ID (default: Rt-estimation-<timestamp>-<uuid>)'
      task_exclusions:
        description: 'Task exclusions (state:disease pair - default: None; ex: NY:COVID-19)'
      output_container:
        description: 'Output container in Azure (default: nssp-rt-testing)'

env:
  # Together, these form: cfaprdbatchcr.azurecr.io/cfa-config-generator
  REGISTRY: cfaprdbatchcr.azurecr.io/
  IMAGE_NAME: cfa-config-generator
  MAIN_BRANCH_NAME: main

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    secrets: inherit

  run-workload:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: branch-name

      - name: Figure out tag (either latest if it is main or the branch name)
        shell: bash
        id: image-tag
        run: |
          if [ "${{ steps.branch-name.outputs.branch }}" = "${{ env.MAIN_BRANCH_NAME }}" ]; then
            echo "tag=${{ env.MAIN_BRANCH_NAME }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ steps.branch-name.outputs.branch }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker Image String
        id: image-name
        run: echo "image_name=${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}" >> $GITHUB_OUTPUT

      - name: Trigger Container App Job
        uses: CDCgov/cfa-actions/runner-action@v1.3.0
        with:
          github_app_id: ${{ secrets.CDCENT_ACTOR_APP_ID }}
          github_app_pem: ${{ secrets.CDCENT_ACTOR_APP_PEM }}
          wait_for_completion: true
          print_logs: true
          script: |
            echo "Logging into Azure CLI"
            az login --service-principal \
              --username ${{ fromJSON(secrets.EDAV_CFA_PREDICT_NNHT_SP).clientId }} \
              --password ${{ fromJSON(secrets.EDAV_CFA_PREDICT_NNHT_SP).clientSecret }} \
              --tenant ${{ fromJSON(secrets.EDAV_CFA_PREDICT_NNHT_SP).tenantId }}

            JOB_NAME='cfa-config-generator'
            RESOURCE_GROUP='ext-edav-cfa-prd'
            TEMPLATE='job-template.yaml'

            echo "Getting Existing Job Template"
            az containerapp job show \
              --name "$JOB_NAME" \
              --resource-group "$RESOURCE_GROUP" \
              --query "properties.template" \
              --output yaml > $TEMPLATE

              echo "Updating Job Template"
              yq -i '.containers[0].image = "${{ steps.image-name.outputs.image_name }}"' $TEMPLATE
              yq -i '.containers[0].env += { "name": "state", "value": "${{ inputs.state }}" }' $TEMPLATE
              yq -i '.containers[0].env += { "name": "disease", "value": "${{ inputs.disease }}" }' $TEMPLATE
              yq -i '.containers[0].env += { "name": "reference_dates", "value": "${{ inputs.reference_dates }}" }' $TEMPLATE
              yq -i '.containers[0].env += { "name": "report_date", "value": "${{ inputs.report_date }}" }' $TEMPLATE
              yq -i '.containers[0].env += { "name": "data_container", "value": "${{ inputs.data_container }}" }' $TEMPLATE
              yq -i '.containers[0].env += { "name": "production_date", "value": "${{ inputs.production_date }}" }' $TEMPLATE
              yq -i '.containers[0].env += { "name": "job_id", "value": "${{ inputs.job_id }}" }' $TEMPLATE
              yq -i '.containers[0].env += { "name": "task_exclusions", "value": "${{ inputs.task_exclusions }}" }' $TEMPLATE
              yq -i '.containers[0].env += { "name": "output_container", "value": "${{ inputs.output_container }}" }' $TEMPLATE
              yq -i '.containers[0].command = [ "uv", "run", "python", "pipelines/epinow2/generate_config.py" ]' $TEMPLATE
              cat $TEMPLATE

              echo "Starting Job"
              az containerapp job start \
              --resource-group  "$RESOURCE_GROUP" \
              --name "$JOB_NAME" \
              --yaml $TEMPLATE && echo "Started Container App Job!"
              # throw error if job fails
              if [ $? -ne 0 ]; then
                echo "Failed to start Container App Job!"
                exit 1
              fi
